In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
data = pd.read_excel (r'C:\Users\madhu\Downloads\BikeSharing.xlsx')
df = pd.DataFrame(data, columns= ['instant','hr','mnth','temp','weekday','hum','windspeed'])
print (df)

       instant  hr  mnth  temp  weekday   hum  windspeed
0            1   0     1  0.24        6  0.81     0.0000
1            2   1     1  0.22        6  0.80     0.0000
2            3   2     1  0.22        6  0.80     0.0000
3            4   3     1  0.24        6  0.75     0.0000
4            5   4     1  0.24        6  0.75     0.0000
...        ...  ..   ...   ...      ...   ...        ...
17374    17375  19    12  0.26        1  0.60     0.1642
17375    17376  20    12  0.26        1  0.60     0.1642
17376    17377  21    12  0.26        1  0.60     0.1642
17377    17378  22    12  0.26        1  0.56     0.1343
17378    17379  23    12  0.26        1  0.65     0.1343

[17379 rows x 7 columns]


In [3]:
df.head()

instant  hr  mnth  temp  weekday   hum  windspeed
0        1   0     1  0.24        6  0.81        0.0
1        2   1     1  0.22        6  0.80        0.0
2        3   2     1  0.22        6  0.80        0.0
3        4   3     1  0.24        6  0.75        0.0
4        5   4     1  0.24        6  0.75        0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17379 entries, 0 to 17378
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   instant    17379 non-null  int64  
 1   hr         17379 non-null  int64  
 2   mnth       17379 non-null  int64  
 3   temp       17379 non-null  float64
 4   weekday    17379 non-null  int64  
 5   hum        17379 non-null  float64
 6   windspeed  17379 non-null  float64
dtypes: float64(3), int64(4)
memory usage: 950.5 KB


In [5]:
df.describe()

instant            hr          mnth          temp       weekday  \
count  17379.0000  17379.000000  17379.000000  17379.000000  17379.000000   
mean    8690.0000     11.546752      6.537775      0.496987      3.003683   
std     5017.0295      6.914405      3.438776      0.192556      2.005771   
min        1.0000      0.000000      1.000000      0.020000      0.000000   
25%     4345.5000      6.000000      4.000000      0.340000      1.000000   
50%     8690.0000     12.000000      7.000000      0.500000      3.000000   
75%    13034.5000     18.000000     10.000000      0.660000      5.000000   
max    17379.0000     23.000000     12.000000      1.000000      6.000000   

                hum     windspeed  
count  17379.000000  17379.000000  
mean       0.627229      0.190098  
std        0.192930      0.122340  
min        0.000000      0.000000  
25%        0.480000      0.104500  
50%        0.630000      0.194000  
75%        0.780000      0.253700  
max        1.000000      0.850700

In [6]:
df_train = df[df.instant % 2 != 0]
print(df_train)

       instant  hr  mnth  temp  weekday   hum  windspeed
0            1   0     1  0.24        6  0.81     0.0000
2            3   2     1  0.22        6  0.80     0.0000
4            5   4     1  0.24        6  0.75     0.0000
6            7   6     1  0.22        6  0.80     0.0000
8            9   8     1  0.24        6  0.75     0.0000
...        ...  ..   ...   ...      ...   ...        ...
17370    17371  15    12  0.28        1  0.45     0.1343
17372    17373  17    12  0.26        1  0.48     0.0896
17374    17375  19    12  0.26        1  0.60     0.1642
17376    17377  21    12  0.26        1  0.60     0.1642
17378    17379  23    12  0.26        1  0.65     0.1343

[8690 rows x 7 columns]


In [7]:
df_test = df[df.instant % 5 == 0]
print(df_test)

       instant  hr  mnth  temp  weekday   hum  windspeed
4            5   4     1  0.24        6  0.75     0.0000
9           10   9     1  0.32        6  0.76     0.0000
14          15  14     1  0.46        6  0.72     0.2836
19          20  19     1  0.42        6  0.88     0.2537
24          25   0     1  0.46        0  0.88     0.2985
...        ...  ..   ...   ...      ...   ...        ...
17354    17355  23    12  0.20        0  0.51     0.2239
17359    17360   4    12  0.14        1  0.69     0.1045
17364    17365   9    12  0.18        1  0.64     0.1045
17369    17370  14    12  0.28        1  0.45     0.2239
17374    17375  19    12  0.26        1  0.60     0.1642

[3475 rows x 7 columns]


In [8]:
y_train=df_train['casual']
x_train=df_train[['hr','mnth','temp','weekday','hum','windspeed']]

KeyError: 'casual'

In [ ]:
print(x_train.shape)
print(y_train.shape)

In [ ]:
hr = df_train['hr'].values.tolist() #convert data to list 
len(hr)

In [ ]:
mnth = df_train['mnth'].values.tolist()
len(mnth)

In [ ]:
temp = df_train['temp'].values.tolist()
len(temp)

In [ ]:
weekday = df_train['weekday'].values.tolist()
len(weekday)

In [ ]:
hum = df_train['hum'].values.tolist()
len(hum)

In [ ]:
windspeed = df_train['windspeed'].values.tolist()
len(windspeed)

In [ ]:
casual = df_train['casual'].values.tolist()
len(casual)

In [ ]:
list = []

In [ ]:
#cross correlation

In [85]:
crosscorrel1 = sum([((hr * casual)/8690) for hr,casual in zip(hr,casual)])
print(crosscorrel1)


515.2294591484485


In [88]:
crosscorrel2 = sum([((mnth * casual)/8690) for mnth,casual in zip(mnth,casual)])
print(crosscorrel2)


244.67364787111788


In [87]:
crosscorrel3 = sum([((temp * casual)/8690) for temp,casual in zip(temp,casual)])
print(crosscorrel3)

22.094598388952743


In [90]:
crosscorrel4 = sum([((weekday * casual)/8690) for weekday,casual in zip(weekday,casual)])
print(crosscorrel4)

110.49551208285403


In [91]:
crosscorrel5 = sum([((hum * casual)/8690) for hum,casual in zip(hum,casual)])
print(crosscorrel5)

19.07533256616804


In [174]:
crosscorrel6 = sum([((windspeed * casual)/8690) for windspeed,casual in zip(windspeed,casual)])
print(crosscorrel6)

7.308107836593802


In [96]:

list.append(crosscorrel1)
list.append(crosscorrel2)
list.append(crosscorrel3)
list.append(crosscorrel4)
list.append(crosscorrel5)
list.append(crosscorrel6)
print(list)

[515.2294591484485, 244.67364787111788, 22.094598388952743, 110.49551208285403, 19.07533256616804, 7.308107836593802]


In [148]:
b = np.matrix('515.2294591484485, 244.67364787111788, 22.094598388952743, 110.49551208285403, 19.07533256616804, 7.308107836593802')  # limiting the data-type to int
print('\n matrix is:\n', b)
# using shape attribute to get the tuple describing matrix shape
print('The dimension of the matrix is :', b.shape)



 matrix is:
 [[515.22945915 244.67364787  22.09459839 110.49551208  19.07533257
    7.30810784]]
The dimension of the matrix is : (1, 6)


In [171]:
R0 = b.transpose()
print(R0)
print('The dimension of the matrix R0 is :', R0.shape)

[[515.22945915]
 [244.67364787]
 [ 22.09459839]
 [110.49551208]
 [ 19.07533257]
 [  7.30810784]]
The dimension of the matrix R0 is : (6, 1)


In [ ]:
#correlation matrix

In [144]:
e11 = sum([((hr * hr)/8690) for hr,hr in zip(hr,hr)])
print(e11)
e12 = sum([((hr * mnth)/8690) for hr,mnth in zip(hr,mnth)])
print(e12)
e13 = sum([((hr * temp)/8690) for hr,temp in zip(hr,temp)])
print(e13)
e14 = sum([((hr * weekday)/8690) for hr,weekday in zip(hr,weekday)])
print(e14)
e15 = sum([((hr * hum)/8690) for hr,hum in zip(hr,hum)])
print(e15)
e16 = sum([((hr * windspeed)/8690) for hr,windspeed in zip(hr,windspeed)])
print(e16)

182.8405063291175
75.91829689298012
5.954807825086271
34.85569620253138
6.926104718066819
2.3154127272727183


In [156]:
R1 = np.matrix('182.8405063291175, 75.91829689298012, 5.954807825086271, 34.85569620253138, 6.926104718066819, 2.3154127272727183')  # limiting the data-type to int
print('\n Row1 is:\n', R1) #row 1


 Row1 is:
 [[182.84050633  75.91829689   5.95480783  34.8556962    6.92610472
    2.31541273]]


In [158]:
e21 = e12
print(e21)
e22 = sum([((mnth * mnth)/8690) for mnth,mnth in zip(mnth,mnth)])
print(e22)
e23 = sum([((mnth * temp)/8690) for mnth,temp in zip(mnth,temp)])
print(e23)
e24 = sum([((mnth * weekday)/8690) for mnth,weekday in zip(mnth,weekday)])
print(e24)
e25 = sum([((mnth * hum)/8690) for mnth,hum in zip(mnth,hum)])
print(e25)
e26 = sum([((mnth * windspeed)/8690) for mnth,windspeed in zip(mnth,windspeed)])
print(e26)

75.91829689298012
54.56973532796136
3.383153049482137
19.712313003452515
4.211239355581131
1.1839857767548843


In [159]:
R2 = np.matrix('75.91829689298012, 54.56973532796136, 3.383153049482137, 19.712313003452515, 4.211239355581131, 1.1839857767548843')  # limiting the data-type to int
print('\n Row2 is:\n', R2) #row 2


 Row2 is:
 [[75.91829689 54.56973533  3.38315305 19.712313    4.21123936  1.18398578]]


In [161]:
e31 = e13
print(e31)
e32 = e23
print(e32)
e33 = sum([((temp * temp)/8690) for temp,temp in zip(temp,temp)])
print(e33)
e34 = sum([((temp * weekday)/8690) for temp,weekday in zip(temp,weekday)])
print(e34)
e35 = sum([((temp * hum )/8690) for temp,hum in zip(temp,hum)])
print(e35)
e36 = sum([((temp * windspeed)/8690) for temp,windspeed in zip(temp,windspeed)])
print(e36)

5.954807825086271
3.383153049482137
0.2841537859608781
1.4920115074798508
0.3092558573072513
0.09379834522439558


In [163]:
R3 = np.matrix('5.954807825086271, 3.383153049482137, 0.2841537859608781, 1.4920115074798508, 0.3092558573072513, 0.09379834522439558')  # limiting the data-type to int
print('\n Row3 is:\n', R3) #row 3


 Row3 is:
 [[5.95480783 3.38315305 0.28415379 1.49201151 0.30925586 0.09379835]]


In [165]:
e41 = e14
print(e41)
e42 = e24
print(e42)
e43 = e34
print(e43)
e44 = sum([((weekday * weekday)/8690) for weekday,weekday in zip(weekday,weekday)])
print(e44)
e45 = sum([((weekday * hum )/8690) for weekday,hum in zip(weekday,hum)])
print(e45)
e46 = sum([((weekday * windspeed )/8690) for weekday,windspeed in zip(weekday,windspeed)])
print(e46)

34.85569620253138
19.712313003452515
1.4920115074798508
13.04487917146127
1.8704948216340522
0.5739500690448739


In [167]:
R4 = np.matrix('34.85569620253138, 19.712313003452515, 1.4920115074798508,  13.04487917146127, 1.8704948216340522, 0.5739500690448739')  # limiting the data-type to int
print('\n Row4 is:\n', R4) #row 4


 Row4 is:
 [[34.8556962  19.712313    1.49201151 13.04487917  1.87049482  0.57395007]]


In [168]:
e51 = e15
print(e51)
e52 = e25
print(e52)
e53 = e35
print(e53)
e54 = e45
print(e54)
e55 = sum([((hum * hum )/8690) for hum,hum in zip(hum,hum)])
print(e55)
e56 = sum([((hum * windspeed )/8690) for hum,windspeed in zip(hum,windspeed)])
print(e56)

6.926104718066819
4.211239355581131
0.3092558573072513
1.8704948216340522
0.43071116225548023
0.11227048653624837


In [169]:
R5 = np.matrix('6.926104718066819, 4.211239355581131, 0.3092558573072513, 1.8704948216340522, 0.43071116225548023, 0.11227048653624837')  # limiting the data-type to int
print('\n Row5 is:\n', R5) #row 5


 Row5 is:
 [[6.92610472 4.21123936 0.30925586 1.87049482 0.43071116 0.11227049]]


In [170]:
e61 = e16
print(e61)
e62 = e26
print(e62)
e63 = e36
print(e63)
e64 = e46
print(e64)
e65 = e56
print(e65)
e66 = sum([((windspeed * windspeed )/8690) for windspeed,windspeed in zip(windspeed,windspeed)])
print(e66)

2.3154127272727183
1.1839857767548843
0.09379834522439558
0.5739500690448739
0.11227048653624837
0.0510117986260058


In [172]:
R6 = np.matrix('2.3154127272727183, 1.1839857767548843, 0.09379834522439558, 0.5739500690448739, 0.11227048653624837, 0.0510117986260058')  # limiting the data-type to int
print('\n Row6 is:\n', R6) #row 6


 Row6 is:
 [[2.31541273 1.18398578 0.09379835 0.57395007 0.11227049 0.0510118 ]]


In [173]:
print(R1)
print(R2)
print(R3)
print(R4)
print(R5)
print(R6)

[[182.84050633  75.91829689   5.95480783  34.8556962    6.92610472
    2.31541273]]
[[75.91829689 54.56973533  3.38315305 19.712313    4.21123936  1.18398578]]
[[5.95480783 3.38315305 0.28415379 1.49201151 0.30925586 0.09379835]]
[[34.8556962  19.712313    1.49201151 13.04487917  1.87049482  0.57395007]]
[[6.92610472 4.21123936 0.30925586 1.87049482 0.43071116 0.11227049]]
[[2.31541273 1.18398578 0.09379835 0.57395007 0.11227049 0.0510118 ]]


In [175]:
y_test=df_test['casual']
x_test=df_test[['hr','mnth','temp','weekday','hum','windspeed']]

In [176]:
print(x_test.shape)
print(y_test.shape)

(3475, 6)
(3475,)
